name: Reset Diário do Space



on:

  schedule:

    # Roda todo dia às 09:00 (Horário de Brasília)

    - cron: '0 2 * * *'

  workflow_dispatch: # Permite rodar manualmente



jobs:

  reset-space:

    runs-on: ubuntu-latest  # <--- AQUI ESTAVA O ERRO (agora corrigido para hífen)

    steps:

      - name: Reiniciar Space

        run: |

          curl -X POST https://huggingface.co/api/spaces/sayydaviid/avalia-backend/restart \

          -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}"
